SELECT *
FROM book_info;

COMMIT;
ROLLBACK;

#1
CREATE TABLE BOOK_INFO(
	BOOK_NUM INT PRIMARY KEY,
	TITLE VARCHAR(10) NOT NULL,
	WRITER VARCHAR(10) NOT NULL,
	PRICE INT,
	PUBLISHER VARCHAR(10) DEFAULT '미지정',
	PUB_DATE DATE
);

#2
INSERT INTO book_info
VALUES (101, '자바 기초', '홍길동', 30000, 'A출판', '2025-02-15');

INSERT INTO book_info 
VALUES (102, '리액트 기초', '이순신', 20000, 'B출판', '2025-01-22');

#3
UPDATE book_info
SET
	TITLE = '자바_고급',
	PRICE = 25000,
	PUBLISHER = 'IT출판'
WHERE BOOK_NUM = 101;

#4
SELECT EMPNO, ENAME, SAL, COMM AS 인센티브
FROM emp
WHERE SAL >= 500
AND SAL <= 3000
AND COMM IS NULL;

#5
SELECT EMPNO, ENAME, JOB, HIREDATE
FROM emp
WHERE ENAME LIKE '%병%'
OR ENAME LIKE '%김%'
ORDER BY JOB ASC, EMPNO DESC;

#6
SELECT EMPNO, ENAME, DEPTNO,
	CASE DEPTNO
		WHEN 10 THEN '인사부'
		WHEN 20 THEN '영업부'
		WHEN 30 THEN '개발부'
		ELSE '생산부' END AS 부서명
FROM emp;

#7
SELECT EMPNO, ENAME, TO_CHAR(HIREDATE, 'YYYY.MM.DD HH24.MI.SS') AS HIREDATE
FROM emp
WHERE MONTH(HIREDATE) % 2 = 0
AND JOB IN ('사원', '과장', '차장')
ORDER BY HIREDATE ASC;

#8
SELECT EMPNO, ENAME, SAL, COMM, SAL * 12 + IFNULL(COMM, 0) AS TOTAL_SALARY
FROM emp
ORDER BY SAL * 12 + IFNULL(COMM, 0) DESC;

#9
SELECT EMPNO, DEPTNO, SUBSTR(ENAME, 2) AS 이름
FROM emp
WHERE YEAR(HIREDATE) >= 2003
AND YEAR(HIREDATE) <= 2006;
		
#10
SELECT '행의 개수 : 3개' AS 정답;
