
 CREATE TABLE basic_board (
 BOARD_NUM INT PRIMARY KEY AUTO_INCREMENT  #컬럼의값을지정하지않으면자동으로1씩증가된값을넣어주는기능을한다.
 , TITLE VARCHAR(30)
 , WRITER VARCHAR(20)
 , CONTENT VARCHAR(50)
 , READ_CNT INT DEFAULT 0
 , CREATE_DATE DATETIME DEFAULT SYSDATE()
 );
 
 SELECT *
 FROM basic_board;
 
INSERT INTO BASIC_BOARD (TITLE, WRITER, CONTENT)
VALUES ('제목1', '작성자1', '내용1');
INSERT INTO BASIC_BOARD (TITLE, WRITER, CONTENT)
VALUES ('제목2', '작성자2', '내용2');
INSERT INTO BASIC_BOARD (TITLE, WRITER, CONTENT)
VALUES ('제목3', '작성자3', '내용3');

INSERT INTO basic_board(
	TITLE
	, WRITER
	, CONTENT
) VALUES (
	'java 고급'
	, '작성자7'
	, '내용7'
);

SELECT BOARD_NUM
   , TITLE
   , WRITER
   , CREATE_DATE
   , READ_CNT
FROM BASIC_BOARD
WHERE TITLE LIKE '%java%';

COMMIT;
ROLLBACK;

CREATE TABLE BASIC_MEMBER (
	MEM_ID VARCHAR(20) PRIMARY KEY,
	MEM_PW VARCHAR(20) NOT NULL,
	MEM_NAME VARCHAR(10),
	MEM_AGE INT,
	BIRTHDAY DATETIME
);

SELECT *
FROM basic_member;


SELECT *
FROM basic_member WHERE mem_id = 'admin';

SELECT MEM_NAME
FROM basic_member
WHERE MEM_ID = 'korea';