# 자동차 정보
CREATE TABLE CAR_INFO (
	MODEL_NUM INT PRIMARY KEY AUTO_INCREMENT # 모델번호
	, MODEL_NAME VARCHAR(20) NOT NULL # 모델명
	, PRICE INT NOT NULL # 금액
	, CAR_MAKER VARCHAR(20) NOT NULL # 제조사
);

# 자동차판매 정보
CREATE TABLE SALES_INFO (
	SALES_NUM INT PRIMARY KEY AUTO_INCREMENT # 판매번호
	, BUYER VARCHAR(20) NOT NULL # 구매자명
	, BUYER_TEL VARCHAR(20) # 구매자연락처
	, COLOR VARCHAR(10) NOT NULL # 색상
	, SALES_DATE DATETIME DEFAULT SYSDATE() # 판매일
	, MODEL_NUM INT REFERENCES CAR_INFO (MODEL_NUM) # 모델번호
);

SELECT * 
FROM car_info;

SELECT * 
FROM sales_info;
