CREATE TABLE MY_MEMBER(
	MEM_NUM INT PRIMARY KEY,
	MEM_ID VARCHAR(10) NOT NULL,
	MEM_PW VARCHAR(10) NOT NULL,
	MEM_NAME VARCHAR(10) NOT NULL,
	MEM_AGE INT,
	EMAIL_ADDR VARCHAR(20) UNIQUE
);

SELECT *
FROM my_member;

COMMIT;
ROLLBACK;

INSERT INTO my_member
VALUES (102, 'hong', 5678 ,'홍자바', 25, 'hong@gmail.com');

UPDATE my_member
SET
MEM_NAME = '유관순',
MEM_AGE = MEM_AGE + 5
WHERE MEM_NUM = 101;

SELECT EMPNO, ENAME, SAL, COMM
FROM emp
WHERE SAL >= 500
AND SAL <= 3000
AND COMM IS NOT NULL;

SELECT EMPNO, ENAME, HIREDATE
FROM emp
WHERE ENAME LIKE '%기'
OR ENAME LIKE '%김%'
ORDER BY EMPNO DESC;

SELECT 
	EMPNO, 
	ENAME, 
	DEPTNO, 
	CASE DEPTNO
		WHEN 10 THEN '인사부'
		WHEN 20 THEN '영업부'
		WHEN 30 THEN '개발부'
		ELSE '생산부' END AS '부서명'
FROM emp;

SELECT EMPNO, ENAME, HIREDATE, IFNULL(COMM, 0)
FROM emp
ORDER BY HIREDATE ASC;
