#회원 테이블
CREATE TABLE USERS(
	USER_ID VARCHAR(20) PRIMARY KEY #아이디
	, USER_PW VARCHAR(20) NOT NULL #비밀번호
	, USER_NAME VARCHAR(20) NOT NULL #사용자 이름
	, USER_TEL VARCHAR(15) #연락처
	, USER_EMAIL VARCHAR(50) UNIQUE #이메일
	, USER_ROLE VARCHAR(10) NOT NULL DEFAULT 'PERSONAL' #사용자 유형 : PERSONAL(개인), ADMIN(관리자)
	, CREATE_DATE DATETIME DEFAULT SYSDATE() #가입일자
);

#서비스 신청 테이블
CREATE TABLE APPLICATION(
	APPL_NUM INT PRIMARY KEY AUTO_INCREMENT #신청번호
	, APPL_ROLE VARCHAR(15) NOT NULL #신청자 유형 : PERSONAL(개인), CORPORATE(법인)
	, BUSINESS_TEL VARCHAR(15) NOT NULL #실무자 연락처
	, APPL_ADDR VARCHAR(50) NOT NULL #신청자 주소
	, ADDR_DETAIL VARCHAR(50) NOT NULL #신청자 주소 상세
	, CONTENT VARCHAR(100) #상담 내용
	, USER_ID VARCHAR(20) REFERENCES users (USER_ID) # 회원 아이디
);	

# 라즈베리파이 데이터 테이블
CREATE TABLE growing_environment(
	TEMPER_NUM INT PRIMARY KEY AUTO_INCREMENT,
	TEMPER FLOAT NOT NULL,
	HUMIDITY FLOAT NOT NULL,
	SOIL_HUMIDITY FLOAT NOT NULL, 
	ILLUMINATION INT NOT NULL,
	CREATE_DATE DATETIME DEFAULT SYSDATE() 
);	

DESC growing_environment;

SELECT * FROM growing_environment;

# 문의 테이블
CREATE TABLE QUESTION(
	QST_ID INT PRIMARY KEY AUTO_INCREMENT # 문의 아이디
	, QST_TITLE VARCHAR(50) NOT NULL      # 문의 제목
	, QST_CONTENT VARCHAR(500) NOT NULL   # 문의 내용
	, USER_ID VARCHAR(10) REFERENCES USERS (USER_ID) ON DELETE CASCADE # 문의자
	, QST_DATE DATETIME DEFAULT SYSDATE() # 작성일
	, QST_STATUS VARCHAR(20) DEFAULT '진행중' # 진행 상태
);

# 문의 테이블 이미지
CREATE TABLE question_img(
	IMG_NUM INT PRIMARY KEY AUTO_INCREMENT # 이미지명
	, ORIGIN_IMG_NAME VARCHAR(100) # 원본 파일명
	, ATTACHED_IMG_NAME VARCHAR(100) # 첨부된 파일명
	, QST_ID INT REFERENCES question(QST_ID) # 이미지 등록자
	, IS_MAIN VARCHAR	(3) # 메인 여부
);

# 답변 테이블
CREATE TABLE ANSWER(
	ANS_ID INT PRIMARY KEY AUTO_INCREMENT # 답변 아이디
	, ANS_TITLE VARCHAR(50) NOT NULL      # 답변 제목
	, ANS_CONTENT VARCHAR(500) NOT NULL   # 답변 내용
	, QST_ID INT REFERENCES QUESTION (QST_ID) ON DELETE CASCADE # 문의 아이디
	, USER_ID VARCHAR(10) REFERENCES USERS (USER_ID) ON DELETE CASCADE # 작성자(관리자)
	, ANS_DATE DATETIME DEFAULT SYSDATE() # 답변 작성일
);