-- 1. 고객 테이블 생성
CREATE TABLE CUSTOMER (
    CUSTOMER_ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(50),
    EMAIL VARCHAR(100),
    CITY VARCHAR(50),
    CREATED_AT DATETIME DEFAULT SYSDATE()
);

-- 2. 주문 테이블 생성 (외래키 사용)
CREATE TABLE ORDERS (
    ORDER_ID INT PRIMARY KEY AUTO_INCREMENT,
    CUSTOMER_ID INT REFERENCES CUSTOMER (CUSTOMER_ID),
    PRODUCT_NAME VARCHAR(100),
    ORDER_CNT INT,
    ORDER_DATE DATETIME DEFAULT SYSDATE() 
);


SELECT * FROM customer;
SELECT * FROM orders;
#1. 고객 이름과 주문한 상품명, 수량을 조회	
SELECT PRODUCT_NAME
	, ORDER_CNT
	, (SELECT NAME
		FROM CUSTOMER
		WHERE CUSTOMER_ID = ORDERS.CUSTOMER_ID) AS NAME
FROM orders;

#2. 고객 "김철수"가 주문한 상품명 조회
SELECT PRODUCT_NAME
FROM orders O
WHERE CUSTOMER_ID IN (SELECT CUSTOMER_ID
							FROM customer C
							WHERE NAME = '김철수');

#3. 고객별 총 주문 수량 조회
SELECT SUM(ORDER_CNT)
	, (SELECT NAME 
		FROM customer C
		WHERE C.CUSTOMER_ID = O.CUSTOMER_ID) NAME 
FROM orders O
GROUP BY CUSTOMER_ID;

#4. 최소 한 번이라도 주문한 고객의 이름 조회
# -> 고객번호가 1,2,3,4번인 사람의 이름을 조회
SELECT NAME
FROM customer C
WHERE (SELECT COUNT(CUSTOMER_ID) 
		FROM orders O
		WHERE O.CUSTOMER_ID = C.CUSTOMER_ID) >= 1
