CREATE TABLE board(
	BOARD_NUM INT PRIMARY KEY AUTO_INCREMENT
	, TITLE VARCHAR(30) NOT NULL
	, WRITER VARCHAR(20) NOT NULL
	, CONTENT VARCHAR(50)
	, READ_CNT INT DEFAULT 0
	, CREATE_DATE DATETIME DEFAULT SYSDATE()
);

SELECT *
FROM board;

# 상품 정보 테이블
CREATE TABLE ITEM (
	ITEM_NUM INT PRIMARY KEY AUTO_INCREMENT
	, ITEM_CATEGORY VARCHAR(30) NOT NULL
	, ITEM_NAME VARCHAR(20) NOT NULL UNIQUE
	, ITEM_PRICE INT NOT NULL
	, ITEM_INTRO VARCHAR(50)
	, ITEM_STATUS VARCHAR(10) # 상품 준비중, 판매중, 매진
	, REG_DATE DATETIME DEFAULT SYSDATE()
);

SELECT *
FROM item;

SELECT SUM(ITEM_PRICE) 
FROM item;