CREATE TABLE BOOK(
	BOOK_NUM INT  PRIMARY KEY AUTO_INCREMENT,
	TITLE VARCHAR(20) NOT NULL UNIQUE,
	CATEGORY VARCHAR(20) NOT NULL,
	WRITER VARCHAR(20) NOT NULL,
	PRICE INT,
	PUBLISH_DATE DATETIME DEFAULT SYSDATE(),
	RENT_CNT INT
);

SELECT *
FROM book;

ROLLBACK;
COMMIT;

INSERT INTO book (TITLE, CATEGORY, WRITER, PRICE, RENT_CNT) 
VALUES ('자바 기초', 'IT/인터넷', '김자바', 10000, 10);

INSERT INTO book (TITLE, CATEGORY, WRITER, PRICE, RENT_CNT) 
VALUES ('일본여행기', '에세이', '윤여행', 7000, 5);

INSERT INTO book (TITLE, CATEGORY, WRITER, PRICE, RENT_CNT) 
VALUES ('재테크 시작하기', '자기계발', '김자바', 15000, 15);

INSERT INTO book (TITLE, CATEGORY, WRITER, PRICE, RENT_CNT) 
VALUES ('리액트 따라하기', 'IT/인터넷', '김자바', 20000, 3);

INSERT INTO book (TITLE, CATEGORY, WRITER, PRICE, RENT_CNT) 
VALUES ('직장인 월급관리', '자기계발', '윤여행', 13000, 8);

DROP TABLE book;

UPDATE book 
SET 
RENT_CNT = RENT_CNT + 5,
PRICE = PRICE + 1000
WHERE WRITER = '윤여행';

# DROP TABLE book;