# 날짜 관련 함수
SELECT NOW(), SYSDATE(), CURRENT_DATE(), CURRENT_TIME;

SELECT YEAR(NOW()), MONTH(NOW()), DAY(NOW());

# EMP테이블에서 2005년 이후에 입사한 사원들의 모든 정보를 조회

SELECT *
FROM emp
WHERE YEAR(HIREDATE) >= 2005;

SELECT 
	HIREDATE
	, TO_CHAR(HIREDATE, 'YYYY.MM.DD HH24:MI:SS')
	, TO_CHAR(HIREDATE, 'YY')
	, YEAR(HIREDATE)
	, TO_CHAR(HIREDATE, 'YYYY-MM-DD')
	, TO_CHAR(HIREDATE, 'YYYYMMDD')
	, CONCAT(TO_CHAR(HIREDATE, 'YYYY'), '년', TO_CHAR(HIREDATE, 'MM'), '월', TO_CHAR(HIREDATE, 'DD'), '일') AS 입사일
FROM emp;

# IF문
SELECT IF(10 > 2, '참', '거짓');

# IFNULL() -> NULL을 특정 값으로 치환
SELECT COMM, IFNULL(COMM, 0) FROM emp;

SELECT COUNT(EMPNO), COUNT(COMM) FROM emp;

SELECT AVG(SAL), AVG(COMM), AVG(IFNULL(COMM,0)) FROM emp;

SELECT 
	EMPNO, 
	ENAME, 
	DEPTNO,
	CASE DEPTNO 
		WHEN 10 THEN '인사부'
		WHEN 20 THEN '영업부'
		WHEN 30 THEN '개발부'
		ELSE '생산부' END AS '부서명'
FROM emp;