# 자동차 정보
CREATE TABLE CAR_INFO (
	MODEL_NUM INT PRIMARY KEY AUTO_INCREMENT
	, MODEL_NAME VARCHAR(20) NOT NULL
	, PRICE INT NOT NULL
	, CAR_MAKER VARCHAR(20) NOT NULL
);

# 자동차판매 정보
CREATE TABLE SALES_INFO (
	SALES_NUM INT PRIMARY KEY AUTO_INCREMENT
	, BUYER VARCHAR(20) NOT NULL
	, BUYER_TEL VARCHAR(20)
	, COLOR VARCHAR(10) NOT NULL
	, SALES_DATE DATETIME DEFAULT SYSDATE()
	, MODEL_NUM INT REFERENCES CAR_INFO (MODEL_NUM)
);

SELECT * 
FROM car_info;

SELECT * 
FROM sales_info;
