# 연습용 테이블
# 1. 학급 정보
CREATE TABLE CLASS_INFO (
	CLASS_NUM INT PRIMARY KEY 					  # 학급 번호
	, CLASS_NAME VARCHAR(20) NOT NULL UNIQUE # 학급명
);

CREATE TABLE STUDENT_INFO (
	STU_NUM INT PRIMARY KEY AUTO_INCREMENT
	, STU_NAME VARCHAR(20) NOT NULL
	, STU_AGE INT 
	, CLASS_NUM INT REFERENCES CLASS_INFO (CLASS_NUM)
);

INSERT INTO CLASS_INFO 
VALUES (1, '자바반');
INSERT INTO CLASS_INFO 
VALUES (2, '영상반');
INSERT INTO CLASS_INFO 
VALUES (3, '디자인반');

INSERT INTO STUDENT_INFO VALUES(1, '김자바', 20, 1);
INSERT INTO STUDENT_INFO VALUES(2, '윤자바', 30, 1);
INSERT INTO STUDENT_INFO VALUES(3, '정자바', 40, 1);

INSERT INTO STUDENT_INFO VALUES(4, '김영상', 20, 2);
INSERT INTO STUDENT_INFO VALUES(5, '윤영상', 30, 2);
INSERT INTO STUDENT_INFO VALUES(6, '정영상', 40, 2);

INSERT INTO STUDENT_INFO VALUES(7, '김디자인', 20, 3);
INSERT INTO STUDENT_INFO VALUES(8, '윤디자인', 30, 3);
INSERT INTO STUDENT_INFO VALUES(9, '정디자인', 40, 3);
