CREATE TABLE apt(
	UNIT INT PRIMARY KEY,
	RESI_CNT INT DEFAULT 1,
	PROPERTY INT,
	RESI_OWN VARCHAR(10) NOT NULL,
	CAR INT DEFAULT 0,
	RESI_DATE DATE DEFAULT (CURRENT_DATE)
);

SELECT *
FROM apt;

ROLLBACK;
COMMIT;

INSERT INTO apt(UNIT, RESI_CNT, PROPERTY, RESI_OWN, CAR, RESI_DATE)
VALUES (301, 2, 25000, '이', 1, '2024-10-1');

INSERT INTO apt(UNIT, RESI_CNT, PROPERTY, RESI_OWN, RESI_DATE)
VALUES (303, 3, 50000, '권', '2013-12-19');

INSERT INTO apt(UNIT, RESI_CNT, RESI_OWN, CAR, RESI_DATE)
VALUES (306, 2, '성', 1, '2024-11-22');

INSERT INTO apt(UNIT, RESI_CNT, PROPERTY, RESI_OWN, CAR)
VALUES (301, 4, 88000, '김', 2);

#  김씨와 이씨가 아닌 소유주인 모든 컬럼을 이름 오름차순으로 조회
SELECT *
FROM apt
WHERE !(RESI_OWN LIKE '이%'
OR RESI_OWN LIKE '김%')
ORDER BY RESI_OWN ASC;

SELECT *, (CAR * 10000) + PROPERTY AS TOTAL_PROPERTY, CONCAT(UNIT, '호의 총 재산은 ', (CAR * 10000) + PROPERTY, ' 원입니다.')
FROM apt
ORDER BY (CAR * 10000) + PROPERTY DESC;

SELECT * 
FROM apt
ORDER BY PROPERTY DESC;

SELECT *
FROM apt;

ROLLBACK;
COMMIT;

UPDATE apt
SET
PROPERTY = PROPERTY + 9000,
CAR = CAR + 1
WHERE UNIT = 105;

UPDATE apt
SET 
CAR = 0
WHERE UNIT = 106;