CREATE TABLE orders(
	ORDER_ID INT PRIMARY KEY AUTO_INCREMENT,
	CUST_ID VARCHAR(10),
	ORDER_DATE DATETIME DEFAULT SYSDATE(),
	ADDRESS VARCHAR(20) NOT NULL,
	PRICE INT NOT NULL,
	QTY INT DEFAULT 1
);

SELECT *
FROM orders;

INSERT INTO orders (CUST_ID, ADDRESS, PRICE, QTY)
VALUES ('C010', 'DAEJEON', 12000, 3);

ROLLBACK;
COMMIT;

SELECT *
FROM orders
WHERE PRICE >= 15000
AND QTY >= 3;

SELECT *
FROM orders
WHERE ADDRESS IN ('Seoul', 'Busan');

SELECT *
FROM orders
WHERE PRICE <= 20000
AND QTY = 1;

SELECT *
FROM orders
WHERE ADDRESS = 'Ulsan'
AND PRICE = 16000;

SELECT *
FROM orders
WHERE QTY >= 5
AND PRICE >= 25000;

UPDATE orders
SET
PRICE = 13500
WHERE CUST_ID = 'C003';

UPDATE orders
SET
QTY = 2
WHERE ADDRESS = 'Busan';

SELECT *, PRICE * QTY AS TOTAL
FROM orders;

SELECT *, PRICE * QTY AS TOTAL_COST
FROM orders
WHERE PRICE >= 20000;

UPDATE orders
SET
ADDRESS = UPPER(ADDRESS);

SELECT *
FROM orders
WHERE ADDRESS = 'SEOUL'
ORDER BY PRICE DESC;

SELECT *
FROM orders
WHERE PRICE >= 15000
AND QTY >= 2
ORDER BY QTY ASC;

SELECT *
FROM orders
WHERE ADDRESS IN ('BUSAN', 'DAEJEON')
ORDER BY CUST_ID ASC;

UPDATE orders
SET
QTY = 5
WHERE PRICE = 16000;