CREATE TABLE BASIC_BOARD(
	BOARD_NUM INT PRIMARY KEY AUTO_INCREMENT
	, TITLE VARCHAR(30)
	, WRITER VARCHAR(20)
	, CONTENT VARCHAR(50)
	, READ_CNT INT DEFAULT 0
	, CREATE_DATE DATETIME DEFAULT SYSDATE()
);

SELECT *
FROM basic_board;

