CREATE TABLE BASIC_BOARD(
	BOARD_NUM INT PRIMARY KEY AUTO_INCREMENT
	, TITLE VARCHAR(30)
	, WRITER VARCHAR(20)
	, CONTENT VARCHAR(50)
	, READ_CNT INT DEFAULT 0
	, CREATE_DATE DATETIME DEFAULT SYSDATE()
);

SELECT *
FROM basic_board;

basic_boardCREATE TABLE BASIC_MEMBER(
	MEM_ID VARCHAR(10) PRIMARY KEY
	, MEM_PW VARCHAR(20) NOT NULL
	, MEM_NAME VARCHAR(20) NOT NULL
	, MEM_AGE INT NOT NULL
	, BIRTHDAY DATE DEFAULT CURRENT_DATE
);

SELECT *
FROM basic_member;

COMMIT;

INSERT INTO basic_member (
	MEM_ID
	, MEM_PW
	, MEM_NAME
	, MEM_AGE
) VALUES (
	'LSH'
	, '1234'
	, '승형'
	, 20
);