
# 1. 회원정보 테이블
CREATE TABLE mem (
	MEM_ID VARCHAR(10) PRIMARY KEY
	, MEM_PW VARCHAR(20) NOT NULL
	, MEM_NAME VARCHAR(10) NOT NULL
	, MEM_GENDER VARCHAR(5)
	, MEM_ADDR VARCHAR(50) 
	, ADDR_DETAIL VARCHAR(30) 
	, MEM_TEL VARCHAR(20) 
	, MEM_IDEN VARCHAR(20) NOT NULL
	, MEM_EMAIL VARCHAR(30) UNIQUE
	, REG_DATE DATETIME DEFAULT SYSDATE()
	, MEM_ROLE VARCHAR(20) DEFAULT 'USER'
);

SELECT * 
FROM mem;

# 2. 옷 카테고리 테이블
CREATE TABLE CLOTHING_CATEGORY(
	CATE_NUM INT PRIMARY KEY AUTO_INCREMENT
	, CATE_NAME VARCHAR(20) NOT NULL UNIQUE
);

INSERT INTO CLOTHING_CATEGORY VALUES (1, '상의');
INSERT INTO CLOTHING_CATEGORY VALUES (2, '하의');
INSERT INTO CLOTHING_CATEGORY VALUES (3, '악세사리');

# 3. 옷 테이블
CREATE TABLE CLOTHING(
	CLOTHING_NUM INT PRIMARY KEY AUTO_INCREMENT
	, CLOTHING_NAME VARCHAR(20) NOT NULL
	, BRAND VARCHAR(20) NOT NULL
	, PRICE INT NOT NULL
	, REG_DATE DATETIME DEFAULT SYSDATE() # 쇼핑몰에 상품 등록한 날짜
	, CLOTHING_INTRO VARCHAR(50)
	, CATE_NUM INT REFERENCES CLOTHING_CATEGORY (CATE_NUM)
);

SELECT *
FROM clothing;

SELECT *
FROM clothing_category;

# 4. 장바구니 테이블
CREATE TABLE MEM_CART(
	CART_NUM INT PRIMARY KEY AUTO_INCREMENT
	, CLOTHING_NUM INT REFERENCES clothing (CLOTHING_NUM)
	, CART_CNT INT NOT NULL
	, TOTAL_PRICE INT NOT NULL
	, CART_DATE DATETIME DEFAULT SYSDATE()
	, MEM_ID VARCHAR(10) REFERENCES mem (MEM_ID) 
);
SELECT *
FROM MEM_CART;