
# 1. 회원정보 테이블
CREATE TABLE mem (
	MEM_ID VARCHAR(10) PRIMARY KEY
	, MEM_PW VARCHAR(20) NOT NULL
	, MEM_NAME VARCHAR(10) NOT NULL
	, MEM_GENDER VARCHAR(5)
	, MEM_ADDR VARCHAR(50) 
	, ADDR_DETAIL VARCHAR(30) 
	, MEM_TEL VARCHAR(20) 
	, MEM_IDEN VARCHAR(20) NOT NULL
	, MEM_EMAIL VARCHAR(30) UNIQUE
	, REG_DATE DATETIME DEFAULT SYSDATE()
	, MEM_ROLE VARCHAR(20) DEFAULT 'USER'
);

SELECT * 
FROM mem;

# 2. 옷 카테고리 테이블
CREATE TABLE CLOTHING_CATEGORY(
	CATE_NUM INT PRIMARY KEY AUTO_INCREMENT
	, CATE_NAME VARCHAR(20) NOT NULL UNIQUE
);

INSERT INTO CLOTHING_CATEGORY VALUES (1, '상의');
INSERT INTO CLOTHING_CATEGORY VALUES (2, '하의');
INSERT INTO CLOTHING_CATEGORY VALUES (3, '악세사리');

# 3. 옷 테이블
CREATE TABLE CLOTHING(
	CLOTHING_NUM INT PRIMARY KEY AUTO_INCREMENT
	, CLOTHING_NAME VARCHAR(20) NOT NULL
	, BRAND VARCHAR(20) NOT NULL
	, PRICE INT NOT NULL
	, REG_DATE DATETIME DEFAULT SYSDATE() # 쇼핑몰에 상품 등록한 날짜
	, CLOTHING_INTRO VARCHAR(50)
	, CATE_NUM INT REFERENCES CLOTHING_CATEGORY (CATE_NUM)
);

# 4. 옷 이미지 정보 테이블
CREATE TABLE CLOTHING_IMG (
	IMG_NUM INT PRIMARY KEY AUTO_INCREMENT
	, ORIGIN_IMG_NAME VARCHAR(100) # 원본 파일명
	, ATTACHED_IMG_NAME VARCHAR(100) # 첨부된 파일명
	, CLOTHING_NUM INT REFERENCES CLOTHING (CLOTHING_NUM) ON DELETE CASCADE # 이미지의 원본 도서 번호
	, IS_MAIN VARCHAR(3) # 메인이미지면 : 'Y', 서브이미지 : 'N'
);

SELECT *
FROM clothing;

SELECT *
FROM clothing_img;

SELECT *
FROM clothing_category;

# 5. 장바구니 테이블
CREATE TABLE MEM_CART(
	CART_NUM INT PRIMARY KEY AUTO_INCREMENT
	, CLOTHING_NUM INT REFERENCES clothing (CLOTHING_NUM)
	, CART_CNT INT NOT NULL
	, TOTAL_PRICE INT NOT NULL
	, CART_DATE DATETIME DEFAULT SYSDATE()
	, MEM_ID VARCHAR(10) REFERENCES mem (MEM_ID) 
);
SELECT *
FROM mem_cart;

CREATE TABLE MEM_BUY (
	BUY_NUM INT PRIMARY KEY AUTO_INCREMENT
	, CLOTHING_NUM INT REFERENCES clothing (CLOTHING_NUM)
	, MEM_ID VARCHAR(20) REFERENCES mem (MEM_ID)
	, BUY_DATE DATETIME DEFAULT SYSDATE()
	, BUY_CNT INT 
	, ORDER_NUM INT
);

SELECT * FROM mem_buy;

CREATE TABLE QUESTION(
	QST_ID INT PRIMARY KEY AUTO_INCREMENT
	, QST_TITLE VARCHAR(50) NOT NULL
	, QST_CONTENT VARCHAR(500) NOT NULL
	, MEM_ID VARCHAR(10) REFERENCES mem (MEM_ID) ON DELETE CASCADE
	, QST_DATE DATETIME DEFAULT SYSDATE()
	, QST_STATUS VARCHAR(20) DEFAULT '진행중'
);

CREATE TABLE QUESTION_IMG(
	IMG_NUM INT PRIMARY KEY AUTO_INCREMENT
	, ORIGIN_IMG_NAME VARCHAR(100) # 원본 파일명
	, ATTACHED_IMG_NAME VARCHAR(100) # 첨부된 파일명
	, QST_ID INT REFERENCES question(QST_ID)
	, IS_MAIN VARCHAR(3)
);

CREATE TABLE answer(
	ANS_ID INT PRIMARY KEY AUTO_INCREMENT
	, ANS_TITLE VARCHAR(50) NOT NULL
	, ANS_CONTENT VARCHAR(500) NOT NULL
	, QST_ID INT REFERENCES QUESTION (QST_ID) ON DELETE CASCADE
	, MEM_ID VARCHAR(10) REFERENCES mem (MEM_ID) ON DELETE CASCADE
	, ANS_DATE DATETIME DEFAULT SYSDATE()
);

SELECT * FROM question;
SELECT * FROM question_img;
