SELECT DISTINCT JOB, DEPTNO
FROM emp;

SELECT COMM, IFNULL(COMM, 0)
FROM emp;

SELECT *
FROM emp
WHERE YEAR(HIREDATE) >= 2005;

SELECT *
FROM emp
WHERE TO_CHAR(HIREDATE, 'YYYY') >= 2005;

SELECT *, 
	CASE DEPTNO
		WHEN 10 THEN '인사부'
		WHEN 20 THEN '영업부'
		WHEN 30 THEN '개발부'
		ELSE '생산부' END
		AS 부서명
FROM emp;

SELECT EMPNO, DEPTNO, ENAME, SAL, COMM 
FROM emp
WHERE COMM IS NOT NULL;

SELECT DEPTNO, ENAME, HIREDATE
FROM emp
WHERE ENAME LIKE '%김%'

OR ENAME LIKE '%기'
ORDER BY HIREDATE DESC;

SELECT EMPNO
, ENAME
, DEPTNO
, CASE DEPTNO
	WHEN 10 THEN '인사부'
	WHEN 20 THEN '영업부'
	WHEN 30 THEN '개발부'
	ELSE '생산부' END AS 부서명
FROM emp;

SELECT EMPNO, ENAME, HIREDATE, IFNULL(COMM, 0) AS COMM
FROM emp;

SELECT EMPNO
	, ENAME
	, SAL
	, (SELECT DNAME 
		FROM DEPT
		WHERE DEPTNO = E.DEPTNO) DNAME
FROM emp E
WHERE JOB != '사장';

SELECT EMPNO
	, ENAME
	, HIREDATE
	, SAL
	, DEPTNO
	, (SELECT DNAME
		FROM DEPT
		WHERE DEPTNO = E.DEPTNO) DNAME
FROM emp E
WHERE (SELECT DNAME
		FROM DEPT
		WHERE DEPTNO = E.DEPTNO) = '인사부';

SELECT EMPNO
	, ENAME
	, HIREDATE
	, SAL
	, E.DEPTNO
	, DNAME
FROM emp E
INNER JOIN dept D
ON D.DEPTNO = E.DEPTNO
WHERE DNAME != '인사부'
AND SAL >= 500;