CREATE TABLE my_member(
	MEM_NUM INT PRIMARY KEY,
	MEM_ID VARCHAR(10) NOT NULL,
	MEM_PW VARCHAR(10) NOT NULL,
	MEM_NAME VARCHAR(10) NOT NULL,
	MEM_AGE INT,
	MEM_ADDR VARCHAR(20) UNIQUE
);

INSERT INTO my_member
VALUES (102, 'hong', '5678', '홍자바', 25, 'hong@gmail.com');

SELECT *
FROM my_member;

UPDATE my_member
SET
MEM_NAME = '유관순',
MEM_AGE = MEM_AGE + 5
WHERE MEM_NUM = 101;

COMMIT;

SELECT EMPNO, ENAME, SAL, COMM
FROM emp
WHERE SAL >= 300
AND SAL <= 500
AND COMM IS NOT NULL;

SELECT EMPNO, ENAME, HIREDATE
FROM emp
WHERE ENAME LIKE '%기'
OR ENAME LIKE '%김%'
ORDER BY EMPNO DESC;