SELECT DISTINCT JOB, DEPTNO
FROM emp;

SELECT COMM, IFNULL(COMM, 0)
FROM emp;

SELECT *
FROM emp
WHERE YEAR(HIREDATE) >= 2005;

SELECT *
FROM emp
WHERE TO_CHAR(HIREDATE, 'YYYY') >= 2005;

SELECT *, 
	CASE DEPTNO
		WHEN 10 THEN '인사부'
		WHEN 20 THEN '영업부'
		WHEN 30 THEN '개발부'
		ELSE '생산부' END
		AS 부서명
FROM emp;