CREATE TABLE BOARD(
	BOARD_NUM INT PRIMARY KEY AUTO_INCREMENT
	, TITLE VARCHAR(30) NOT NULL
	, WRITER VARCHAR(20) NOT NULL
	, CONTENT VARCHAR(50)
	, READ_CNT INT DEFAULT 0
	, CREATE_DATE DATETIME DEFAULT SYSDATE()
);

SELECT *
FROM board;

CREATE TABLE ITEM (
	ITEM_NUM INT PRIMARY KEY AUTO_INCREMENT
	, ITEM_CATEGORY VARCHAR(30) NOT NULL
	, ITEM_NAME VARCHAR(20) NOT NULL UNIQUE
	, ITEM_PRICE INT NOT NULL
	, ITEM_INTRO VARCHAR(500)
	, ITEM_STATUS VARCHAR(10)
	, REG_DATE DATETIME DEFAULT SYSDATE()
);

SELECT *
FROM item;
